version: '3.8'

services:
  mastra:
    build:
      context: .
      dockerfile: docker/mastra/Dockerfile
    image: mastra-mcp
    container_name: mastra-mcp
    ports:
      - '4111:4111'
    environment:
      # コンテナ間の接続にはホスト名（localhost）ではなく、サービス名（postgresql）を使用
      - POSTGRES_CODING_ANTIPATTERN_CONNECTION=postgresql://user:password@postgresql:5432/coding_antipattern_vectordb
    depends_on:
      - postgresql
    command: "npm run dev"
    volumes:
      - ./:/app
      - mcp_node_modules:/app/node_modules
  postgresql:
    build:
      context: .
      dockerfile: docker/postgresql/Dockerfile
    image: mcp-pgvector-db
    container_name: mcp-pgvector-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: coding_antipattern_vectordb
    ports:
      - '5432:5432'
    volumes:
      - mcp_pgdata:/var/lib/postgresql/data

volumes:
  mcp_pgdata:
  mcp_node_modules: